-- MySQL Script generated by MySQL Workbench
-- lun. 16 déc. 2019 22:31:03 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id_user` INT(11) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  PRIMARY KEY (`id_user`))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list` ;

CREATE TABLE IF NOT EXISTS `list` (
  `id_list` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `user` INT(11) NOT NULL,
  `listname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_list`, `user`),
  INDEX `fk_list_user1_idx` (`user` ASC),
  CONSTRAINT `fk_list_user1`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

CREATE TABLE IF NOT EXISTS `task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `list` INT NOT NULL,
  `taskname` VARCHAR(45) NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`id_task`),
  INDEX `fk_task_list_idx` (`list` ASC),
  INDEX `fk_task_user1_idx` (`user` ASC),
  CONSTRAINT `fk_task_list`
    FOREIGN KEY (`list`)
    REFERENCES `list` (`id_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_user1`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
